### ISSUE TITLE
feature/fhs branch produces crippled linuxdeployqt

### ISSUE THREAD

**Issue by probonopd** [probonopd/linuxdeployqt#47] opened 2016-11-20 13:28 UTC
The `feature/fhs` branch produces crippled linuxdeployqt. It just segfaults. Is `patchelf` causing this?

**Comment by probonopd** [comment] 2016-12-04 12:23
Reported upstream at https://github.com/NixOS/patchelf/issues/110

**Comment by probonopd** [comment] 2017-02-08 05:12
There is demand for this in #65

**Comment by ubruhin** [comment] 2017-02-12 16:05
I have just tried this branch out, and it worked perfectly with my FHS-like AppDir! But I used the `patchelf` version from the official Ubuntu repository, I have not compiled it by myself.

As I can see, you bundle `linuxdeployqt` with a self-compiled version of `patchelf`, using their `master` branch. In my opinion this is not very smart, because the `master` branch is not considered as stable in many projects (I don't know if this also applies to `patchelf`). I would use the latest stable release instead (just checkout a specific tag after cloning the patchelf's repository).

Maybe this would already solve the problem with the segfault... I would love to see the `feature/fhs` branch merged into `master` as soon as possible :smiley:

**Comment by probonopd** [comment] 2017-02-12 19:12
Oh wow, that is very interesting indeed! Will try to use Ubuntu's patchelf. Which exact patched version for which Ubuntu version did you use?

**Comment by ubruhin** [comment] 2017-02-12 21:06
I have used this version: http://packages.ubuntu.com/xenial/patchelf

Now I'm trying to reproduce the results on Travis-CI, but unfortunately on their Ubuntu Trusty this package is not available...

**Comment by probonopd** [comment] 2017-02-13 00:33
Check this one, https://github.com/probonopd/linuxdeployqt/releases/download/fhs/linuxdeployqt-continuousfhs-x86_64.AppImage - it uses patchelf_0.8.orig.tar.gz from Ubuntu (although compiled by me on Travis CI).

**Comment by ubruhin** [comment] 2017-02-13 00:45
> Check this one

Doesn't work (segmentation fault) :(

Btw. I had problems with stripped binaries, so I always passed `-no-strip` to `linuxdeployqt`. Maybe this is the cause for the segfault?

**Comment by probonopd** [comment] 2017-02-13 00:46
My only question is, why does this happen only with the `feature/fhs` branch?

**Comment by ubruhin** [comment] 2017-02-13 00:50
Maybe because of [this line](https://github.com/probonopd/linuxdeployqt/blob/feature/fhs/.travis.yml#L36) which does not exist in the `master` branch:

```
strip linuxdeployqt.AppDir/usr/bin/* || continue
```

**Comment by probonopd** [comment] 2017-02-14 22:23
FHS-like mode is now implemented, please try https://github.com/probonopd/linuxdeployqt/releases/tag/continuous

**Comment by ubruhin** [comment] 2017-02-18 15:33
Seems to be fixed, so I think this issue can be closed...

**Closed** 2017-02-18 17:39 UTC
Labels: bug

**Comment by probonopd** [comment] 2017-04-24 17:53
With https://github.com/NixOS/patchelf/pull/117 merged, patchelf will hopefully allow binaries to be stripped after running patchelf.
