### ISSUE TITLE
Error "Network Service Crashed, Restarting Service" is displayed when QWebEngineView is used 

### ISSUE THREAD

**Issue by muse117** [probonopd/linuxdeployqt#506] opened 2021-10-12 12:24 UTC
Error "Network Service Crashed, Restarting Service" is displayed when QWebEngineView is used.
Running the program in the Builder directory is fine  

![微信截图_20211012202221](https://user-images.githubusercontent.com/9733486/136955321-b9ddfbf5-24d6-4e92-972e-e2884f78bf0d.png)

**Comment by probonopd** [comment] 2021-10-12 17:02
Possibly the well-known `libsoftoken3.so` issue, is this ticket a duplicate of [the existing ones](https://github.com/probonopd/linuxdeployqt/search?q=libsoftokn3.so&type=issues)? If not please comment here to reopen. Thanks

**Closed as completed by probonopd** 2021-10-12 17:02 UTC
