### ISSUE TITLE
Relax GLIBC requirements for Qt6.2

### ISSUE THREAD

**Issue by Dekker1** [probonopd/linuxdeployqt#517] opened 2021-12-05 21:59 UTC
We are trying to upgrade our deployment of our Qt application to Qt6.2 (at least for supported platforms); however, we are running into the maximum GLIBC requirement of `linuxdeployqt`: 

```
linuxdeployqt 6 (commit d41e234), build 724 built on 2020-07-31 15:51:47 UTC
ERROR: The host system is too new.
Please run on a system with a glibc version no newer than what comes with the oldest
currently still-supported mainstream distribution (xenial), which is glibc 2.23.
```

I understand the reasoning behind using this versioning requirement, and it will likely help users. However, the suggested version and other distributions with similar GLIBC versions are no longer supported by the Qt distributions: https://doc.qt.io/qt-6/linux.html
As such, I was hoping that this requirement could in some way be relaxed.

My preferred solution is to have an additional flag to set the "Maximum GLIBC version". This can still remain set at its current value, but can be changed by the packager when required. This could still output a stern warning stating that "using a newer version of GLIBC limits the compatibility of the packaged application".

Otherwise, I would suggest that `linuxdeployqt` should at least allow the GLIBC versions with which the official Qt distribution (of a specific version) is compiled. It seems very strange to me for the packaging script to require more compatibility that Qt itself guarantees.

**Comment by probonopd** [comment] 2021-12-08 19:48
> It seems very strange to me for the packaging script to require more compatibility that Qt itself guarantees.

Our policy is that AppImages should at least run on all still-supported LTS releases of Ubuntu. Personally I think this is a reasonable policy and applciation authors who wish to use `linuxdeployqt` should stay away from Qt versions that are not guaranteed to run on all still-supported LTS releases of Ubuntu.

This being said, there are other tools that can work around this by bundling more into the AppImage, so that the resulting AppImages can run even on systems older than the system the binaries inside the AppImage were built on. So, if your particular use case requires the use of a newer Qt version than is available for the oldest still-supported LTS release of Ubuntu, I'd encourage you to check out those tools, e.g.,:

* AppImageBuilder
* go-appimage `appimagetool -s deploy`

Closing as a duplicate of https://git.io/JDTzw.

**Closed by probonopd** 2021-12-08 19:48 UTC
