### ISSUE TITLE
Run ldd on Qt plugins as well

### ISSUE THREAD

**Issue by lrineau** [probonopd/linuxdeployqt#49] opened 2016-11-28 13:21 UTC
_First, thanks for this tool. I have managed to use it on a rather big Qt5 application (one app, 73 loadable plugins, 25 shared libraries), and it worked (though I have not yet tried the AppImage feature). To make it work, I have listed all the loadable plugins with extra `-executable=` options. Yet I had to use a workaround for one thing, and that is what this issue report is about..._

When one uses the option `-bundle-non-qt-libs`, the lib dependencies (but the core ones listed in the exclude ist) are bundled. That allows to create a portable bundle of the application (which is the purpose of `linuxdeployqt`). But it seems that the dependencies of the Qt plugins are not checked. In my case, I compiled the application on CentOS 6, with Qt5 from the official EPEL RPM repository. The `libqxcb.so` Qt plugin NEEDs `libudev.so.0`, but that library is not bundled. I had to copy it manually, to be able to run the bundled application on another Linux version (Fedora 24). Probably the ldd tool is not used on Qt plugins, and that would explain the bug.

**Comment by lrineau** [comment] 2016-11-28 13:34
FYI, the application is from [CGAL] (also [on GitHub]), in the `Polyhedron/demo/Polyhedron/` sub-directory. I am currentlly building a Docker image that allows the automatic building of the bundle (and maybe also the AppImage).

[CGAL]: http://www.cgal.org 
[on GitHub]: http://github.com/CGAL/cgal

**Comment by probonopd** [comment] 2016-11-29 20:00
This might be caused by https://github.com/probonopd/linuxdeployqt/issues/25 - simply run the same `linuxdeployqt` command twice. Does it work then?

**Comment by probonopd** [comment] 2017-02-18 20:09
@lrineau I assume this is caused by #25. Please comment here if you think otherwise.

**Comment by probonopd** [comment] 2017-02-20 00:53
Might be the same as https://github.com/probonopd/linuxdeployqt/issues/75#issuecomment-280964272

**Comment by probonopd** [comment] 2017-03-27 18:05
I can confirm this, by using https://github.com/probonopd/QtQuickApp as the application under test.

Whenever these two numbers don't match it indicates that we haven't properly deployed (set rpath and copied dependencies) all .so files, which is a `linuxdeployqt` problem.

```
me@host:~/squashfs-root$ find usr/plugins -name '*.so*' -exec grep '$ORIGIN' {} \; | wc -l
9
me@host:~/squashfs-root$ find usr/plugins/ -name '*.so*' | wc -l
16
```

**Comment by probonopd** [comment] 2017-03-27 18:06
Duplicate of https://github.com/probonopd/linuxdeployqt/issues/5, hence closing here. Let's continue in #5.

**Closed by probonopd** 2017-03-27 18:07 UTC
