### ISSUE TITLE
Hangs whet specified a QML dir

### ISSUE THREAD

**Issue by denis-shienkov** [probonopd/linuxdeployqt#248] opened 2018-03-05 18:18 UTC
linuxdeployqt utility hangs more tnan ~10 minuts when specified a QML directory flag, e.g.:

/opt/qt510/bin/linuxdeployqt myapp -qmldir=<path/to/myapp/qml/sources>

OS: Ubuntu 16.04 32 bit
Qt: 5.10.0 installed to /opt/qt510 (from ppa: https://launchpad.net/~beineri/+ppa-packages)
linuxdeployqt: From git e915ad00eeeb61a96c77b27367c9195f8940473b

**Comment by TheAssassin** [comment] 2018-03-05 18:19
Please provide a full log. Try to re-run with `-verbose=3`.

**Comment by denis-shienkov** [comment] 2018-03-05 18:36
[non-full.log](https://github.com/probonopd/linuxdeployqt/files/1782130/non-full.log)

I can't attach a full log, as my console is overflowed.

**Comment by TheAssassin** [comment] 2018-03-05 18:41
You know how a pipe redirection works? Re-run with `2>&1 1>log.txt`.

**Comment by TheAssassin** [comment] 2018-03-05 18:41
Or, even better, run with `2>&1 | tee log.txt`. This way, you can see what's going on.

**Comment by denis-shienkov** [comment] 2018-03-05 18:54
[log.txt](https://github.com/probonopd/linuxdeployqt/files/1782182/log.txt)

15 minuts for simple QML application.. O_o

**Comment by TheAssassin** [comment] 2018-03-05 18:56
@denis-shienkov my guess is it's related to the copyright files copying facilities which are more of alpha quality and slow down linuxdeployqt very much. See also #231. I'll have a look at the log whether my assumption is correct.

**Comment by TheAssassin** [comment] 2018-03-05 18:56
Yes, that's the issue. Sorry for the inconvenience. You can't fix the issue at the moment, please be patient with linuxdeployqt.

Closing as duplicate of #231.

**Closed by TheAssassin** 2018-03-05 18:56 UTC

**Comment by denis-shienkov** [comment] 2018-03-05 18:59
Can we just skip the copyright files?

**Comment by TheAssassin** [comment] 2018-03-05 19:01
There is no such switch at the moment, as far as I know. We should add one, or deactivate the whole thing again. It can be useful, but with the way linuxdeployqt works at the moment, its causing more issues than it shou.d

**Comment by probonopd** [comment] 2018-03-05 20:52
Very strange, I did not notice such slowdowns when running `linuxdeployqt` on Travis CI. Please be aware that bundling copyright notices may be a legal requirement.

**Comment by TheAssassin** [comment] 2018-03-05 20:53
@probonopd we discussed that extensively a while ago. I already explained the Travis CI infrastructure is more optimized. You can't compare it to the average computer. I, @azubieta and a lot of others noticed these performance issues, too...
