### ISSUE TITLE
 I wonder if the version of arrh64 can be provided 

### ISSUE THREAD

**Issue by clggxxx** [probonopd/linuxdeployqt#488] opened 2021-05-19 12:40 UTC
in kylin os and arrch64

**Comment by probonopd** [comment] 2021-05-22 10:41
arrh64? arrch64?

More like aarch64.
Could probably be done now that https://docs.travis-ci.com/user/multi-cpu-architectures/ supports arm64. Any volunteers to send a PR?

**Comment by probonopd** [comment] 2021-05-22 10:43
Closing as a duplicate of https://github.com/probonopd/linuxdeployqt/issues/351.

**Closed by probonopd** 2021-05-22 10:43 UTC
