### ISSUE TITLE
Hook into Open Build Service (OBS) similar as you do with Travis CI?

### ISSUE THREAD

**Issue by KurtPfeifle** [probonopd/linuxdeployqt#243] opened 2018-02-27 15:23 UTC
The owner of a GitHub repo can hook in additional external tools similar to hooking in Travis CI.
For this project it would be beneficial to hook in openSUSE's Open Build Service (OBS).
Go to the repo settings (here: https://github.com/probonopd/linuxdeployqt/settings), *"Integration & services"* to see what I mean.

OBS is listed as *"Obs"* in the drop-down list of available services when clicking the *"Add service **`'v'`**"*.

I cannot be of any help to actually set it up (or even to provide a pull request), because so far I failed to wrap my mind around the challenge to understand *at all* how OBS works and how to set it up.

But I guess you know all the beneficial features OBS can potentially provide:

1. Building not only .AppImage, but also RPM, DEB and other formats for lots of native distro package managers. This could be beneficial in order to increase visibility of the AppImage project and to remove some FUD which is spread by certain parties.

2. Building not only for `x86_64`, but also for i586, aarch64 and armvl7. The latter two are especially important in order to get AppImages built for ARM/Raspberry systems. (Currently there are only few ARM AppImages out there; these cannot be auto-updated, because tools like *`zsync2`* 
 and *`appimageupdatetool`* currently are not available for ARM.)

Having the full scope of AppImage creation and handling tools available for ARM would be awesome.

**Comment by probonopd** [comment] 2018-02-27 19:32
Now I am confused, I thought I had answered this question but my answer seems to be lost. There _is_ a way to do this. I think one needs to get a token from OBS and enter it into GitHub.

Are you suggesting

a) that we should explain better to AppImageKit/linuxdeployqt users how to do this; or
b) that we use OBS instead of Travis CI for building AppImageKit/linuxdeployqt itself?

**Comment by TheAssassin** [comment] 2018-02-27 19:56
@probonopd I believe he does suggest to build our tools on OBS and have it generate AppImages (especially for ARM) as well as distro packages.

I do plan to build ARM AppImages and upload them upstream on GitHub releases. This can be done on Travis CI, our current tool. Supporting OBS as a second system adds a lot of maintenance overhead, and requires a lot of work to get started. Also, OBS is not really suitable for continuous integration, it's perfect for release packaging only. It cannot and will not replace a system like Travis.

Furthermore, the OBS team does already provide packages for our tools. And, regarding `.deb/.rpm`, actually we don't want to build any kind of distro package ourselves (the appimaged `.deb` file is more of an "experimental" package, too). AppImages are our way to distribute our tools. If you want distro packaging, you should instead ask the distros to package the tools if you want to.

But, given we have such a small team, a distro packaging of our tools will just lead to the same problems that _any other_ kind of software has seen: super old outdated packages, lacking features, containing ancient bugs. And that leads to authors beginning to create PPAs etc. to have users actually use up to date software, etc...

Remember @dirkhh's comment on Google Plus?

> The AppImage approach is really really useful. It allows us to do on Linux what we can do on the other OSs we support: use the system libraries that are there and bundle the additional pieces that we need.
> 
> Subsurface certainly is a somewhat extreme case as we want very very recent versions of a few libraries (libgit2, Qt5 for example) and we even have our own forks of a couple of libraries because we want to be somewhat "ahead" of upstream.
> 
> But what is not just a Subsurface issue is the other underlying problem: it is a major pain to get an application to be included (and kept current) in dozens of Linux distributions. And from an application perspective what I care about is that my users can use the latest version. Regardless of the release cycle of the distribution, regardless of what the distribution thinks of the libraries that I use in my application.
> 
> So yes, I'm a huge fan of this and think that Simon (probono) has done a really cool job here. I'm sure there's room for improvement (and the colaboration with Simon has been just wonderful so far, so I'm certain things will continue to get better), but the fact that we now can  tell users "oh, just use the AppImage and it will work" is such an improvement.
> 
> Just yesterday a user wasn't able to get things to work on Fedora 23 (which should get a semi-official package of Subsurface 4.5.2, soon, as they are more willing to work with our needs to get our own versions of libdivecomputer and libmarblewidget bundled). But instead of telling them how to work around the issues they ran into the simple solution was "use the AppImage".
> 
> Yay.
> 
> *(source: https://plus.google.com/+LinusTorvalds/posts/WyrATKUnmrS)*

Now, think, how would you feel as both an application developer thinks like "oh dear, we fixed that like a year ago..." or a user who thinks they can use the software in their distro, reports a problem to an app author, and they tell the user to not use the distro packages as they're buggy and outdated? I hate these kinds of discussions. It's a waste of time for both sides. And packaging stuff in PPAs is not the way to go. AppImages solve the developer->user distribution problem efficiently. Let's continue to ship only AppImages.

**Comment by probonopd** [comment] 2018-02-27 20:00
Definitely we should ship AppImages. Actually my preference would be that we continue building on Travis CI but additionally do everything needed so that the awesome team in Nuremberg (and around the world) can happily build the AppImage tools on OBS as well.

**Comment by TheAssassin** [comment] 2018-02-27 20:02
@probonopd sure. I am just saying there won't be an "upstream" packaging for good reasons. If third parties want to build packages, it's their right to do so. Less maintenance work for us. Plus they're more competent in packaging usually.

**Comment by KurtPfeifle** [comment] 2018-02-28 16:50
> Are you suggesting
>
> a) that we should explain better to AppImageKit/linuxdeployqt users how to do this; or
> b) that we use OBS instead of Travis CI for building AppImageKit/linuxdeployqt itself?

Since TravisCI cannot do it, I suggest to use OBS for building the AppImage tools *at least* for ARM (aarch and armv7l). Major problem for the few AppImages for e.g. Raspberry is that they cannot be updated. So to have `appimageupdatetool.AppImage` available is a "minimum".

----

And once we're at it, it would be fast seen just *how easy or how difficult it is* to use OBS. Is that true or is that only propaganda? appimage.org promotes OBS in a video, but hardly can one see any "results", for example in the shape of more AppImages from that.

Also it would start to increase the visibility of the AppImage project if there were some activities in towards embracing OBS in general. This is "more work" in the first instance -- but it could quickly lead to "more helping hands" as well, with some luck. And providing RPMs and DEBs (which is said to be easy once you build ANYTHING with OBS) could help getting the tools into the *"development"* category of distros' software repos, again leading to more exposure/visibility/helpinghands.

**Comment by KurtPfeifle** [comment] 2018-02-28 17:00
<sup>(Possibly unrelated:   
someone just stated that *"linuxdeployqt looked like good solution"*: https://bugs.wireshark.org/bugzilla/show_bug.cgi?id=14464#c4 )</sup>

**Comment by TheAssassin** [comment] 2018-02-28 18:31
> Since TravisCI cannot do it

That's just not true. And contradicts my above statement. It _can_ do it. We just have to configure it to do so.

Don't get me wrong: OBS is great for building AppImages for arbitrary software. But building the tools on OBS is not a viable solution for us. It's always overloaded, and doesn't satisfy the constraints to qualify for a "continuous integration build system". 

I assume you don't have much experience with continuous integration and don't know why OBS is good for packaging but not for continuous integration builds. Please refer to https://en.wikipedia.org/wiki/Continuous_integration for general information on CI, and https://www.martinfowler.com/articles/continuousIntegration.html on best practices. One of them is "fail fast and move on", a core principle of agile development.

And, as said before, we don't really want to ship 20 different formats. We have official AppImages, period. You remember that saying "eat your own dogfood"? Also, _any_ kind of self-made packages won't get into distros. They prefer to do it themselves, from scratch, properly. If you _want_ anything to go in a distro, you need to discuss it with them, and don't have to create your own packages. (I have some experiences with Debian package maintenance, for example.)

If you want to build it on OBS, nothing stops you from doing so. They'll be third party packages like the ones maintained by the OBS team.

Also: Even if we _had_ the knowledge to build packages and would be interested in it, we don't have enough personnel resources for such stuff. Maintaining the current build system is more than enough work, trust me.

Regarding your "mere hopes": @adrianschroeter has been providing the tool set for OBS users (and, therefore, openSUSE users) on OBS for almost a year already. I haven't seen anyone stepping up asking about integration into openSUSE etc. If you can provide some evidence that we could expect a "flood of contributors" skilled in packaging etc., we might reconsider the whole topic.

Really: I have already told you we'll be working on these things one day. It can all be done on Travis CI. 
But, same as for OBS, **someone has to do it**.

@probonopd and I agree we will continue to ship AppImages only (you're not the first one requesting this kind of stuff, and you won't be the last one, this position never changed).
Also, this doesn't have any priority right now. The majority of users uses x86_64.

Closing here. Please subscribe to the "ARM build" ticket for more information on this topic.

**Closed by TheAssassin** 2018-02-28 18:31 UTC

**Comment by adrianschroeter** [comment] 2018-02-28 19:13
On Mittwoch, 28. Februar 2018, 19:31:13 CET wrote TheAssassin:
> > Since TravisCI cannot do it
> 
> That's just not true. And contradicts my above statement. It _can_ do it. We just have to configure it to do so.
> 
> Don't get me wrong: OBS is great for building AppImages for arbitrary software. But building the tools on OBS is not a viable solution for us. It's always overloaded, and doesn't satisfy the constraints to qualify for a "continuous integration build system". 
> 
> I assume you don't have much experience with continuous integration and don't know why OBS is good for packaging but not for continuous integration builds. Please refer to https://en.wikipedia.org/wiki/Continuous_integration for general information on CI, and https://www.martinfowler.com/articles/continuousIntegration.html on best practices. One of them is "fail fast and move on", a core principle of agile development.

not sure which aspect you see here, you need faster builds or guaranteed builds for each commit?

> Also: Even if we _had_ the knowledge to build packages and would be interested in it, we don't have enough personnel resources for such stuff. Maintaining the current build system is more than enough work, trust me.

well, depends what your goal is. If you want your software be part of any maintained distro like I understand here....

> Regarding your "mere hopes": @adrianschroeter has been providing the tool set for OBS users (and, therefore, openSUSE users) on OBS for almost a year already. I haven't seen anyone stepping up asking about integration into openSUSE etc. If you can provide some evidence that we could expect a "flood of contributors" skilled in packaging etc., we might reconsider the whole topic.

.... you will need to do classic package packaging. We do prepare for container maintenance, but it will actually require more complexity and contributions then plain container maintenance.
The layer which seem to make it more simple on the short run will make the maintenance way more complex. still possible thought.

Or did you speak about client side tools here?

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by TheAssassin** [comment] 2018-02-28 19:17
> not sure which aspect you see here, you need faster builds or guaranteed builds for each commit?

Fast builds, guaranteed builds, full control about build process, integration with GitHub and other tools like Codacy out of the box, ... OBS is quite limiting us here, it doesn't allow for using our current dependency management but requires them to be integrated in OBS, etc. That's great for building packages, and helps with questions OBS actually tries to solve (like legal questions).

**Comment by adrianschroeter** [comment] 2018-02-28 19:38
On Mittwoch, 28. Februar 2018, 20:18:35 CET wrote TheAssassin:
> > not sure which aspect you see here, you need faster builds or guaranteed builds for each commit?
> 
> Fast builds,

always a constant fight against resources, but you are free to run your own instance :)

> guaranteed builds,

per pull request? There is something in my pipeline, however for gitlab only, since I am not allowed to contribute to github atm due to CLA problems.

> full control about build process

not sure what that means exatly, but if it means random stuff can be downloaded or uploaded during build we will never
support it in our official instance. Since our top #1 goal is reproducability.

> , integration with GitHub

something like this? http://openbuildservice.org/2013/11/22/Source-Update-Via_Token/

> and other tools like Codacy out of the box, ... OBS is quite limiting us here, it doesn't allow for using our current dependency management but requires them to be integrated in OBS, etc. That's great for building packages, and helps with questions OBS actually tries to solve (like legal questions).

well, I don't want to claim that OBS is the best solution for you. It's main goal is reproducability of builds
in a way that you can even rebuild stuff after >10 years in the same way with fixes and for products with lots
of contributors.
It is indeed not designed for projects which focus on one current code base only with just a few contributors.

-- 

Adrian Schroeter
email: adrian@suse.de

SUSE Linux GmbH, GF: Felix Imendörffer, Jane Smithard, Graham Norton, HRB 21284 (AG Nürnberg) 
 
Maxfeldstraße 5                         
90409 Nürnberg 
Germany

**Comment by TheAssassin** [comment] 2018-02-28 19:50
Sure. In no way I was trying to express OBS was a bad tool. Please don't get me wrong. I love OBS and I host my own packaging on it for a couple of things.

It's a matter of responsibility. I don't consider OBS suitable for our style of development, and I guess a lot of people think so, too.

What I want to avoid is having to maintain more than one build system. It is more than enough work to keep our Travis stuff running, and I've invested probably more time than I would have wanted to invest in this already.

I didn't think I had to open that drawer, but:

*Never change a running system!*

**Comment by probonopd** [comment] 2018-03-03 10:10
> What I want to avoid is having to maintain more than one build system. 

I guess that at some point we should have a discussion around the pros and cons of moving the builds _entirely_ to OBS _only_. I would not be surprised to find out that it would mainly be a question of _how much work is needed to port everything over_. In my opinion, OBS clearly produces higher quality results (e.g., in terms of reproduceability and consistency) but like most things this comes at a cost, namely forcing the maintainers to work in a much more systematic (think distro packaging) way.

In any case, we are __highly__ interested in having the AppImage tools work as "good citizens" on OBS and openSUSE (even if we are continuing to do our "official" builds on Travis CI for now, due to pragmatic reasons). Most likely we can only do so with occasional support from @adrianschroeter, which I am very thankful for.

**Comment by TheAssassin** [comment] 2018-03-03 12:09
> I guess that at some point we should have a discussion around the pros and cons of moving the builds entirely to OBS only.

That point is in a faaaaaar away future...
