### ISSUE TITLE
continuous build segfault

### ISSUE THREAD

**Issue by leozide** [probonopd/linuxdeployqt#355] opened 2019-03-09 19:03 UTC
A few days ago linuxdeployqt started segfaulting on my Travis CI builds, for example: https://travis-ci.org/leozide/leocad/jobs/504068863

If I use the latest official release (https://github.com/probonopd/linuxdeployqt/releases/download/6/linuxdeployqt-6-x86_64.AppImage) then it works (disregard the upload error at the end): https://travis-ci.org/leozide/leocad/jobs/504083768

I tried re-running an old build that succeeded and it now fails as well so it looks like something changed in either linuxdeployqt or Travis. Do you have any ideas?

**Comment by probonopd** [comment] 2019-03-09 19:11
Thanks for reporting. I don't know yet what is going on.

**Comment by tcuje** [comment] 2019-03-09 19:47
Same issue for me. How can I debug this?

**Comment by probonopd** [comment] 2019-03-09 20:17
Reverting commit aa78a03, let's see if that will change anything.

**Comment by leozide** [comment] 2019-03-09 20:30
I restarted and it still fails, but this time it displayed some gtk errors before crashing. https://travis-ci.org/leozide/leocad/jobs/504068863

**Comment by probonopd** [comment] 2019-03-09 20:47
What happens if you do

```
apt-get update
apt-get -y install libgtk2.0-dev
git clone http://code.qt.io/qt/qtstyleplugins.git
cd qtstyleplugins
qmake
make -j$(nproc)
sudo make install 
cd -
```

before you run it?

**Comment by probonopd** [comment] 2019-03-09 20:48
I don't think it's crashing anymore?

**Comment by probonopd** [comment] 2019-03-09 20:53
Err, scrap that, it is still segfaulting. So something else must be going on. Can you run with `-verbose=2` please?

**Comment by probonopd** [comment] 2019-03-09 20:55
I think we should bring back commit aa78a03 then.

**Comment by probonopd** [comment] 2019-03-09 21:00
Looks like `appimagetool` is what actually is crashing.

**Comment by leozide** [comment] 2019-03-09 21:01
https://travis-ci.org/leozide/leocad/jobs/504114214 with -verbose=2

**Comment by probonopd** [comment] 2019-03-09 21:18
@tcuje please provide a link to your build logs, thanks.

**Comment by tcuje** [comment] 2019-03-09 21:26
I just have a fork of leozide's and wanted to help out.

**Comment by probonopd** [comment] 2019-03-09 21:56
Now this is interesting. appimagetool 7d45aa3 when being called by linuxdeployqt internally is crashing, the same appimagetool 7d45aa3 when bering called externally seems to be working...

https://travis-ci.com/probonopd/leocad/builds/103791807

**Comment by probonopd** [comment] 2019-03-09 22:29
Please try this:

```
script:
  - qmake PREFIX=/usr -v
  - qmake PREFIX=/usr -r
  - make -j4
  - if [ "$TRAVIS_OS_NAME" != "linux" ] ; then exit 0 ; fi
  - make INSTALL_ROOT=appdir -j$(nproc) install ; find appdir/
  - sed -i -e 's|.svg||g' appdir/usr/share/applications/leocad.desktop # FIXME; .svg should not be in the desktop file to begin with
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" 
  - chmod a+x linuxdeployqt*.AppImage 
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/*.desktop -bundle-non-qt-libs
  - ./linuxdeployqt*.AppImage --appimage-extract
  - export PATH=$(readlink -f ./squashfs-root/usr/bin/):$PATH
  - ./squashfs-root/usr/bin/appimagetool appdir/
```

**Comment by tcuje** [comment] 2019-03-09 23:24
lets see: https://travis-ci.org/tcuje/leocad/builds/504149647

**Comment by tcuje** [comment] 2019-03-09 23:32
That worked!
Can you link/explain more about that svg FIXME? Is there a related issue?

**Comment by leozide** [comment] 2019-03-10 00:16
The workaround works for me too, thanks for the quick reply.

**Comment by probonopd** [comment] 2019-03-10 07:28
> Can you link/explain more about that svg FIXME? Is there a related issue?

Instead if `Icon=leocad.svg`, the desktop file should have `Icon=leocad`.

**Comment by tcuje** [comment] 2019-03-10 09:03
Is that a special case for linuxdeployqt? Googling for examples I always saw filenames ending with png or svg

**Comment by probonopd** [comment] 2019-03-10 09:17
Without the filename extension it will work for linuxdeployqt and everywhere else. With the filename extension it will not work for linuxdeployqt.

**Comment by robert7** [comment] 2019-03-10 16:15
hi @probonopd 
I'm also getting "segfault" in https://travis-ci.com/robert7/nixnote2/builds/103787250
`WARNING: Plugin "/usr/lib/x86_64-linux-gnu/qt5/plugins/platformthemes/libqgtk2.so" not found, skipping
WARNING: Plugin "/usr/lib/x86_64-linux-gnu/qt5/plugins/styles/libqgtk2style.so" not found, skipping
appimagetool, continuous build (commit 7d45aa3), build 2046 built on 2019-02-11 22:41:20 UTC
Segmentation fault (core dumped)`


In my desktop file I'm not using extension.. so I'm not sure, what is the fix.
Desktop file: https://github.com/robert7/nixnote2/blob/master/nixnote2.desktop

**Comment by probonopd** [comment] 2019-03-10 17:05
@robert7 please try https://github.com/probonopd/linuxdeployqt/issues/355#issuecomment-471228074

**Comment by Fulgen301** [comment] 2019-03-10 17:51
I also got the segfaults (https://travis-ci.org/Fulgen301/LCEdit/builds/504346503#L890):
```WARNING: Plugin "/opt/qt511/plugins/platformthemes/libqgtk2.so" not found, skipping
WARNING: Plugin "/opt/qt511/plugins/styles/libqgtk2style.so" not found, skipping
appimagetool, continuous build (commit 7d45aa3), build 2046 built on 2019-02-11 22:41:20 UTC
Segmentation fault (core dumped)```
I have an icon referenced without suffix in the desktop file. The workaround did the trick.

**Comment by robert7** [comment] 2019-03-10 18:15
@probonopd it worked, thank you!
https://travis-ci.com/robert7/nixnote2/jobs/183669791

**Comment by Calinou** [comment] 2019-03-12 18:42
The workaround I applied based doesn't seem to be working:

```
squashfs-root/.DirIcon
squashfs-root/AppRun
squashfs-root/linuxdeployqt.desktop
squashfs-root/linuxdeployqt.svg
squashfs-root/usr
squashfs-root/usr/bin
squashfs-root/usr/bin/appimagetool
squashfs-root/usr/bin/desktop-file-validate
squashfs-root/usr/bin/linuxdeployqt
squashfs-root/usr/bin/patchelf
squashfs-root/usr/bin/qt.conf
squashfs-root/usr/bin/zsyncmake
squashfs-root/usr/lib
squashfs-root/usr/lib/appimagekit
squashfs-root/usr/lib/appimagekit/mksquashfs
squashfs-root/usr/lib/libQt5Core.so.5
squashfs-root/usr/lib/libicudata.so.52
squashfs-root/usr/lib/libicui18n.so.52
squashfs-root/usr/lib/libicuuc.so.52
squashfs-root/usr/lib/libpcre.so.3
squashfs-root/usr/share
squashfs-root/usr/share/doc
squashfs-root/usr/share/doc/libicu52
squashfs-root/usr/share/doc/libicu52/copyright
squashfs-root/usr/share/doc/libpcre3
squashfs-root/usr/share/doc/libpcre3/copyright
squashfs-root/usr/share/doc/qt59base
squashfs-root/usr/share/doc/qt59base/copyright
squashfs-root/usr/translations
linuxdeployqt 6 (commit cfa4dc5), build 653 built on 2019-03-09 21:04:59 UTC
Desktop file as first argument: "appdir/godot.desktop"
desktopExecEntry: "godot"
desktopIconEntry: "godot"
Found binary from desktop file: "/builds/Calinou/godot-builds-ci/godot/appdir/usr/bin/godot"
FHS-like mode with PREFIX, fhsPrefix: "/builds/Calinou/godot-builds-ci/godot/appdir/usr"
app-binary: "/builds/Calinou/godot-builds-ci/godot/appdir/usr/bin/godot"
appDirPath: "/builds/Calinou/godot-builds-ci/godot/appdir"
relativeBinPath: "usr/bin/godot"
Found icons from desktop file: ("/builds/Calinou/godot-builds-ci/godot/appdir/usr/share/icons/godot.svg")
iconToBeUsed: "/builds/Calinou/godot-builds-ci/godot/appdir/usr/share/icons/godot.svg"
Copied "/builds/Calinou/godot-builds-ci/godot/appdir/usr/share/icons/godot.svg" to "/builds/Calinou/godot-builds-ci/godot/appdir/godot.svg"
appimagetool, continuous build (commit 7d45aa3), build 2046 built on 2019-02-11 22:41:20 UTC
Segmentation fault (core dumped)
```

**Comment by probonopd** [comment] 2019-03-16 15:18
Could 
https://gitlab.com/inkscape/inkscape/commit/eadce286758e292efa59a53ef0aefbf885a5d19c#note_148472603 also be caused by this?

Could the root cause be in `appimagetool` rather than in `linuxdeployqt`?

**Comment by Calinou** [comment] 2019-03-16 16:19
> Could the root cause be in appimagetool rather than in linuxdeployqt?

I'm inclined to think the issue is in `appimagetool` indeed.

**Comment by probonopd** [comment] 2019-03-16 18:21
Temporarily using an older build of `appimagetool` now: https://github.com/probonopd/linuxdeployqt/commit/d59e58356a8cb1bd8649a7c3857afa7d5ae6feee

Would appreciate some confirmations that this indeed does fix the issue. Then we know that we have to search for the issue in `appimagetool`.

**Comment by probonopd** [comment] 2019-03-17 13:09
Confirmed that `appimagetool` is at fault.
https://github.com/AppImage/AppImageKit/issues/934#issuecomment-473664138

For now, reverted back to using an older version of `appimagetool`.

**Comment by bjorn** [comment] 2020-10-21 13:56
@probonopd With AppImage/AppImageKit#934 closed, I guess this issue can be closed as well?

**Comment by probonopd** [comment] 2020-10-21 21:40
Thanks @bjorn. Anyone: Feel free to ping me if ou think it should be reopened.

**Closed by probonopd** 2020-10-21 21:40 UTC
