### ISSUE TITLE
ERROR: ldd outputLine: "libicui18n.so.56 => not found"

### ISSUE THREAD

**Issue by don-prog** [probonopd/linuxdeployqt#220] opened 2018-01-25 05:52 UTC
I want to use your tool, but this command:
`./linuxdeployqt-continuous-x86_64.AppImage /home/user/QtProjects/build-VPSTest-Desktop_Qt_5_6_0_GCC_64bit-Release/VPSTest`

Outputs this:

> Not using FHS-like mode
> app-binary: "/home/user/QtProjects/build-VPSTest-Desktop_Qt_5_6_0_GCC_64bit-Release/VPSTest"
> appDirPath: "/home/user/QtProjects/build-VPSTest-Desktop_Qt_5_6_0_GCC_64bit-Release"
> relativeBinPath: "VPSTest"
> ERROR: ldd outputLine: "libicui18n.so.56 => not found"
> ERROR: for binary: "/home/user/QtProjects/build-VPSTest-Desktop_Qt_5_6_0_GCC_64bit-Release/lib//libQt5Core.so.5"
> ERROR: Please ensure that all libraries can be found by ldd. Aborting.

Next I did this:
`ldd libQt5Core.so.5`

This command outputs this:

> 	linux-vdso.so.1 =>  (0x00007fff7e5c1000)
> 	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007ff552c43000)
> 	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007ff552a29000)
> 	libicui18n.so.56 => not found
> 	libicuuc.so.56 => not found
> 	libicudata.so.56 => not found
> 	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007ff552823000)
> 	libgthread-2.0.so.0 => /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0 (0x00007ff552621000)
> 	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007ff552419000)
> 	libglib-2.0.so.0 => /lib/x86_64-linux-gnu/libglib-2.0.so.0 (0x00007ff552109000)
> 	libstdc++.so.6 => /usr/lib/x86_64-linux-gnu/libstdc++.so.6 (0x00007ff551d87000)
> 	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007ff551a7f000)
> 	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007ff551867000)
> 	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007ff55149d000)
> 	/lib64/ld-linux-x86-64.so.2 (0x0000562d67831000)
> 	libpcre.so.3 => /lib/x86_64-linux-gnu/libpcre.so.3 (0x00007ff55122f000)

Next I opened `/home/user/Qt/5.6/gcc_64/lib/`, this is location of the `libQt5Core.so.5`, and of course I found `libicui18n.so.56`, `libicuuc.so.56` and `libicudata.so.56`.

So, how can I fix this issue and create deployment bundle using your tool?

**Comment by TheAssassin** [comment] 2018-01-25 05:57
I suppose that the Qt libs don't have their rpath set properly.

How did you install Qt? Is there perhaps a script like `env.sh` that you have to use like `source path/to/qt/env.sh` to have some environment variables available?

linuxdeployqt is relying on tools like qmake, and if variables like `PATH` don't include the right directories for your non-system Qt, linuxdeployqt is most likely trying to use your system's Qt tools. Same goes for directories like library dirs.

ldd confirms this assumption to some extent:

```
libicui18n.so.56 => not found
libicuuc.so.56 => not found
libicudata.so.56 => not found
```

Those libraries are shipped with Qt, but if you don't have the right environment variables set before running linuxdeployqt, well, it won't work as intended.

**Comment by don-prog** [comment] 2018-01-25 06:08
@TheAssassin, understood, thanks for the fast reply.
But unfortunately I can't find `env.sh` file in the `/home/user/Qt`. `ls` outputs:

> 5.6             Examples             MaintenanceTool.dat  update.rcc
> components.xml  InstallationLog.txt  MaintenanceTool.ini
> dist            Licenses             network.xml
> Docs            MaintenanceTool      Tools
Also, search in this location did not give anything too.

**Comment by TheAssassin** [comment] 2018-01-25 06:09
It could have a similar name or so. I also asked how you installed Qt, maybe I can try to reproduce your issue then.

**Comment by don-prog** [comment] 2018-01-25 06:30
@TheAssassin, unfortunately I still can't find it. There are two options as I did it: using `apt-get install` or using Qt online installer, and I'm almost sure that I did it using online installer.

**Comment by TheAssassin** [comment] 2018-01-25 06:34
Well, you certainly didn't install it using apt. Do you have a link to that online installer thing?

**Comment by don-prog** [comment] 2018-01-25 06:39
@TheAssassin, yes, I think [this is it](http://download.qt.io/archive/online_installers/2.0/qt-unified-linux-x64-2.0.3-online.run).

**Comment by TheAssassin** [comment] 2018-01-25 06:40
Is there docs about it? I don't really want to run some random executable on my system without knowing what it does.

**Comment by don-prog** [comment] 2018-01-25 06:48
I found only [this](http://doc.qt.io/qt-5/gettingstarted.html):

> You can use the Qt installers to download and install the following components:
> 
> - Qt libraries, prebuilt for a particular development platform (operating system and compiler)
> -  Qt Creator integrated development environment (IDE)
>  - Reference Documentation and examples
>  - Qt in source code form (needed only if you want to build the framework and tools yourself)
> - Add-On components that are relevant for different platforms
> 
> After downloading, start the installer like any executable on the development platform.
> 
> To run the installer, you need a Qt Account. You can use your Qt Account credentials to sign-in to all Qt services, including the forums and wiki. If you do not already have a Qt Account, you can create one during the installation process.
> 
> To complete the installation, select the components that you want to install and follow the instructions of the installation program.
> 
> Use the Maintenance Tool under <install_dir> to add components and to update or remove installed components.

**Comment by TheAssassin** [comment] 2018-01-25 16:16
See https://doc-snapshots.qt.io/qt5-dev/linux-building.html, step 4 "environment variables". As mentioned before, you need to set up your PATH. Seems to work in my VM.

But if you want to get rid of all this hassle, maybe use the Qt PPA for Ubuntu? We use that all the time, and our experiences with them are all positive. See [this page](https://launchpad.net/~beineri) for an overview of the versions kindly provided by Stephan Binner.

**Comment by TheAssassin** [comment] 2018-01-25 16:16
Closing for now as this is not a linuxdeployqt but a Qt usage issue. Feel free to reopen if you disagree.

**Closed by TheAssassin** 2018-01-25 16:16 UTC

**Comment by robert7** [comment] 2018-06-28 07:04
I had similar issue.
for me the solution was just to use "-qmake" parameter and point it to locally installed qmake (and not to default system qmake)

example: linuxdeployqt rs-qt5-tutorial-notepad -qmake=/d/dev/Qt/5.5/gcc_64/bin/qmake

**Comment by probonopd** [comment] 2018-06-28 16:13
Would `export PATH=/d/dev/Qt/5.5/gcc_64/bin/:$PATH` have done the job in your case as well @robert7?

**Comment by robert7** [comment] 2018-06-28 19:37
so one more time - before I had Makefile generated by system qmake.
1: with -qmake param without path modification => OK
2: with path modification without -qmake param => ERROR: ldd outputLine: "libicui18n.so.54 => not found"

[qtdeploy1-v2.log](https://github.com/probonopd/linuxdeployqt/files/2146706/qtdeploy1-v2.log)
[qtdeploy2-v2.log](https://github.com/probonopd/linuxdeployqt/files/2146707/qtdeploy2-v2.log)

**Comment by probonopd** [comment] 2018-06-28 20:59
Interesting. Thanks for posting here. It'll certainly be of use to other users.
