### ISSUE TITLE
Qt files are not bundled without -bundle-non-qt-libs

### ISSUE THREAD

**Issue by evpo** [probonopd/linuxdeployqt#39] opened 2016-11-03 11:49 UTC
When running `linuxdeployqt encryptpad`, Qt files are missing from the build directory.
```
./lib
./lib/libicudata.so.55
./lib/libicui18n.so.55
./lib/libicuuc.so.55
./AppRun
./encryptpad
```

If I use `-bundle-non-qt-libs`, linuxdeployqt copies more files including the Qt files.

Environment:
```
$ qmake --version
QMake version 3.0
Using Qt version 5.4.2 in /usr/lib/x86_64-linux-gnu
```

**Comment by probonopd** [comment] 2016-11-03 16:00
Thanks for pointing this out. I am not 100% sure whether we should treat `libicu*` files as Qt files, since they are not strictly Qt-specific. What do people think?

**Comment by Larpon** [comment] 2016-11-04 17:20
libicu* files are distributed with the online installers - I'd presume they're "part" of Qt then?

**Comment by probonopd** [comment] 2016-11-04 19:57
Actually, `libicu*`should already now be bundled according to [this](https://github.com/probonopd/linuxdeployqt/blob/5c79e30f1973fef33c4dfb25d7e467b1abea0317/shared/shared.cpp#L224-L244) source code.

Or did I read this wrong and you are saying libicu* _is_ bundled but other libQt* libraries are not? In this case, you might have ran into https://github.com/probonopd/linuxdeployqt/issues/28 which in the meantime has been addressed.

**Comment by Larpon** [comment] 2016-11-04 21:39
The online installers as of 5.7 has these libs (.so) files bundled under the installed lib/ directory:

(this list is excluding all symlinks and .la and .a files - only .so files). Mind you that symlinks exists in the form *.so.5 and *.so.5.7

```
./libQt53DQuickRender.so.5.7.0
./libqgsttools_p.so.1.0.0
./libQt5Concurrent.so.5.7.0
./libQt53DRender.so.5.7.0
./libQt5WebChannel.so.5.7.0
./libQt5Network.so.5.7.0
./libQt53DLogic.so.5.7.0
./libQt5MultimediaWidgets.so.5.7.0
./libQt5Svg.so.5.7.0
./libQt5Widgets.so.5.7.0
./libQt5Nfc.so.5.7.0
./libQt5MultimediaQuick_p.so.5.7.0
./libQt53DQuick.so.5.7.0
./libQt5EglDeviceIntegration.so.5.7.0
./libQt5QuickControls2.so.5.7.0
./libQt5QuickTest.so.5.7.0
./libQt5WebSockets.so.5.7.0
./libQt5QuickParticles.so.5.7.0
./libQt5Quick.so.5.7.0
./libQt5XcbQpa.so.5.7.0
./libQt5QuickTemplates2.so.5.7.0
./libicuuc.so.56.1
./libQt53DCore.so.5.7.0
./libQt5WebView.so.5.7.0
./libQt5DBus.so.5.7.0
./libQt5XmlPatterns.so.5.7.0
./libQt5Qml.so.5.7.0
./libQt5Gui.so.5.7.0
./libQt5SerialPort.so.5.7.0
./libQt53DQuickInput.so.5.7.0
./libQt5Sql.so.5.7.0
./libQt5OpenGL.so.5.7.0
./libQt5QuickWidgets.so.5.7.0
./libQt5Designer.so.5.7.0
./libQt5PrintSupport.so.5.7.0
./libQt5Positioning.so.5.7.0
./libQt5Test.so.5.7.0
./libicudata.so.56.1
./libQt5Help.so.5.7.0
./libQt53DExtras.so.5.7.0
./libQt53DInput.so.5.7.0
./libQt5Core.so.5.7.0
./libQt5DesignerComponents.so.5.7.0
./libicui18n.so.56.1
./libQt5Multimedia.so.5.7.0
./libQt53DQuickExtras.so.5.7.0
./libQt5X11Extras.so.5.7.0
./libQt5Bluetooth.so.5.7.0
./libQt5Sensors.so.5.7.0
./libQt5CLucene.so.5.7.0
./libQt5Location.so.5.7.0
./libQt5Xml.so.5.7.0
```

So I'm suggesting, since the *official* installers include them, that they should be considered as part of Qt - or Qt-specific. I seem to recall that they are used for the Qt translation system? So anything using string translation should have these included? Vague guess :)

**Comment by probonopd** [comment] 2016-11-04 21:47
Correct; `appimaged` should bundle those if the particular app that is about to be bundled requires them to run. So `appimaged` is not blindly copying every of those, but only the specific ones that are needed. If that doesn't work, that's a bug.

Can you give concrete step-by-step instructions so that I can reproduce your issue? (e.g., which OS are you on, which Qt are you using etc.)

**Comment by Larpon** [comment] 2016-11-05 11:18
I don't have any issues with this - just trying to provide some information.

Maybe @evpo could elaborate on how to reproduce the issue :)

**Comment by probonopd** [comment] 2016-11-05 11:29
Yes, that'd be helpful. Thanks.

**Comment by evpo** [comment] 2016-11-06 02:21
Apologies everyone. I was not clear in my bug description. I meant to say that `libicu*` files were present and `libQt5*` were missing and gave the output of `find` command to show the bundled files.

Since the problem has been addressed in #28, I am closing the issue.

**Comment by evpo** [comment] 2016-11-06 11:59
Tested with the latest [revistion](https://github.com/probonopd/linuxdeployqt/commit/5c79e30f1973fef33c4dfb25d7e467b1abea0317) and observed the same behaviour. Hence, I am reopening the issue.

In addition to the above environment, I also tested with Qt5.3.2 installed from the Qt website official download.

**Comment by probonopd** [comment] 2016-11-06 12:03
What does `qmake` say? Please post detailed step-by-step instructions so that we can reproduce this.

**Comment by evpo** [comment] 2016-11-06 12:22
```
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=15.10
DISTRIB_CODENAME=wily
DISTRIB_DESCRIPTION="Ubuntu 15.10"
```

```
QMake version 3.0
Using Qt version 5.3.2 in /usr/local/Qt5.3.2/5.3/gcc_64/lib
```

1. Install Qt from [the official Qt5.3.2 download](http://download.qt.io/archive/qt/5.3/5.3.2/qt-opensource-linux-x64-5.3.2.run).

2. Clone linuxdeployqt

```
cd linuxdeployqt
qmake
make

cd ..
mkdir epad_deploy
cd epad_deploy
mkdir AppDir
cp ../encryptpad ./AppDir

../linuxdeployqt/linuxdeployqt/linuxdeployqt ./AppDir/encryptpad
```

The result as in the first message above.

**Comment by probonopd** [comment] 2016-11-06 12:24
Please retry with Qt 5.7

**Comment by evpo** [comment] 2016-11-06 12:28
I need an earlier version than 5.7 because of [this issue](https://github.com/evpo/EncryptPad/issues/46)

**Comment by probonopd** [comment] 2016-11-06 12:32
Ugh, so far I don't know the reason for #31 but feel free to investigate.

**Comment by evpo** [comment] 2016-11-06 12:34
I can try Qt5.5 or Qt5.6. It seems the gtk plugin problem did not manifest with them.

**Comment by probonopd** [comment] 2016-11-06 12:38
Might have a chance with 5.6

**Comment by evpo** [comment] 2016-11-06 12:39
On the other hand, `-bundle-non-qt-libs` also solves my problem. If you don't plan to support ancient versions of Qt, I am happy to close this bug. Maybe we can mention the earliest version with which we have successfully tested the tool.

**Comment by probonopd** [comment] 2016-11-06 12:42
Now that is really, __really__ strange and might give us a hint as to why #31 occurs.

**Comment by probonopd** [comment] 2016-11-06 13:02
I think the culprit may be [here](https://github.com/probonopd/linuxdeployqt/blob/5c79e30f1973fef33c4dfb25d7e467b1abea0317/shared/shared.cpp#L241), this is why it refuses to bundle libaries in /usr even if they are Qt libraries. Need to add a condition "... or library name starts with libQt".

**Comment by evpo** [comment] 2016-11-06 13:10
Yes, it may be the problem. My other system Qt installation is also under `/usr`:

```
Log:  dylib.binaryPath "/usr/lib/x86_64-linux-gnu/libQt5Widgets.so.5"
Log:  dylib.binaryPath "/usr/lib/x86_64-linux-gnu/libQt5Gui.so.5"
Log:  dylib.binaryPath "/usr/lib/x86_64-linux-gnu/libQt5Core.so.5"
```

**Comment by probonopd** [comment] 2017-02-18 17:58
@evpo is this still en issue? Please retest, should be fixed by https://github.com/probonopd/linuxdeployqt/commit/a680de5b2b07d89207a8bd46da6ce08e2a69406a. Thanks @atehxx

**Comment by probonopd** [comment] 2017-04-03 20:50
Closing, as this should be fixed by a680de5. @evpo please comment and reopen if the problem persists in the latest continuous build of `linuxdeployqt`.

**Closed by probonopd** 2017-04-03 20:50 UTC
Labels: bug

**Comment by haampie** [comment] 2019-05-23 16:18
I was hoping to deploy an app without `libicudata` since it is quite big. Is it really necessary to keep it with the qt libraries?

**Comment by probonopd** [comment] 2019-05-23 16:34
Make a bundle, then delete libicudata and see if it still runs on your target system(s)...
