### ISSUE TITLE
Running via a wrapper script

### ISSUE THREAD

**Issue by orbifx** [probonopd/linuxdeployqt#135] opened 2017-06-07 16:16 UTC
How can one wrap the main executable with a script which sets environmental variables and provides arguments to main executable?

**Comment by probonopd** [comment] 2017-06-07 16:49
Delete the `AppRun` symlink and replace it by a bash script that launches the application. In doing so, ensure that the bash script works regardless of which directory the user executing it currently is (i.e., the script must determine the path to "itself" and determine the path to the executable to be launched from there).

Something like this:

```
#!/bin/bash
HERE="$(dirname "$(readlink -f "${0}")")"
export LD_LIBRARY_PATH=${HERE}/usr/lib/foobar:$LD_LIBRARY_PATH
exec "${HERE}/usr/bin/codeblocks.wrapper" "$@"
```

**Comment by orbifx** [comment] 2017-06-12 14:21
And the desktop file? Should it the exec field point to the actual program or the wrapper?

**Comment by probonopd** [comment] 2017-06-12 14:27
If you are using a custom `AppRun` file, then you can enter `Exec=AppRun` in the desktop file.

**Comment by orbifx** [comment] 2017-06-12 14:39
With
```
[Desktop Entry]
Name=XYZ
Exec=AppRun
Icon=emblem-downloads
```

I get:

```
Desktop file as first argument: "appdir/usr/share/applications/xyz.desktop"
desktopExecEntry: "AppRun"
desktopIconEntry: "emblem-downloads"
ERROR: Could not determine the path to the executable based on the desktop file
```

**Comment by orbifx** [comment] 2017-06-12 14:57
I'm combining my building with this:

https://github.com/probonopd/linuxdeployqt/issues/134#issuecomment-306854048

**Comment by probonopd** [comment] 2017-06-12 19:56
After these modifications, don't run `linuxdeployqt` anymore, but `appimagetool`.

**Comment by orbifx** [comment] 2017-06-13 09:47
I had to copy the `.desktop` file in `apps/` as well as `apps/usr/share/applications`.

My final error to solve (I hope) is that my wrapper script can't run the main executable (`No such file or directory`). The executable is there. Investigating.

**Comment by TheAssassin** [comment] 2017-06-13 10:05
I guess you fell victim to a quite common misunderstanding. Let me guess: you're running the binary from `AppRun` using a path relative to the script?

The problem is that the AppImage's CWD (current working directory) is not the one it is mounted to later, but the one from which it is called. You will have to resolve this directory from your `AppRun` script.

Please have a look at my `AppRun` script for Red Eclipse: https://github.com/TheAssassin/redeclipse-appimage/blob/master/AppRun
Beware that you should not copy the `cd` instruction. Instead, call it like `exec $(dirname $(readlink -f $0))/usr/bin/mybinary`.

**Comment by orbifx** [comment] 2017-06-13 10:23
No, thankfully there is documentation about that and I avoided it.

The problem seems to be that the wrapper script is installed into `appdir/usr/bin`, so it replaces my main executable. I don't know why the error is about not finding it, but I discovered this by stopping pausing the wrapper script and running the main executable my self.

Does `linuxdeployqt` or `appimagetool` replace the main executable for some reason?

**Comment by orbifx** [comment] 2017-06-13 11:04
It seems that if I overwrite `AppRun` with my wrapper script, then running `appimagetool` replaces my main executable in `bin/` with it too. If I then overwrite my main executable in `bin/` then running `appimagetool` replaces my `AppRun`. Any advice on this?

**Comment by TheAssassin** [comment] 2017-06-13 11:11
Oh, I see. I recently had a similar problem. Turned out that I had to call everything in a specific order. That should fix that problem of you having to copy the desktop file to two locations, too. This is how to do it when using a custom AppRun script:

- Run linuxdeployqt in the AppDir on your desktop file, like `linuxdeployqt ... usr/share/applications/*.desktop`. It'll patch your binary, and create a symlink to it called AppRun in the AppDir. Make sure the desktop file is in that location, and make sure your icon is in `usr/share/icons/hicolor`
- `rm AppRun` to remove the symlink
- copy in your own AppRun
- run appimagetool to create the AppImage

A full working example can be found in my Red Eclipse AppImage project: https://github.com/TheAssassin/redeclipse-appimage/blob/master/build-appimages.sh
Just beware it can build two AppImages at once. You should be able to get the idea.

**Comment by orbifx** [comment] 2017-06-13 11:19
Does it make a difference in `linuxdeployqt` is run from withing _AppDir_ or on the parent?

**Comment by TheAssassin** [comment] 2017-06-13 11:30
I don't think so, I did it that way. You can just try it out I guess. Either it finds the binary relative to the desktop file, or it will display an error.

**Comment by orbifx** [comment] 2017-06-13 11:31
And I presume the `.desktop` has `Exec=<main executable>`?

**Comment by TheAssassin** [comment] 2017-06-13 11:37
Yes. linuxdeployqt will resolve the binary's path automatically.

**Comment by orbifx** [comment] 2017-06-13 13:06
Thanks @TheAssassin, this worked.

**Comment by TheAssassin** [comment] 2017-06-13 13:09
Feel free to close this issue as soon as you finished testing your AppImage on different distributions.

Furthermore, if you encounter further problems, please do not hesitate to reopen this issue.

**Comment by orbifx** [comment] 2017-06-13 13:30
One last issue: does `qmldir` copy the directory? I've tried various values they didn't work. Note my QML directory isn't name `qml`.

**Comment by TheAssassin** [comment] 2017-06-13 13:58
CC @probonopd

I don't have very much experience with linuxdeployqt, but @probonopd will be able to help you with that.

**Comment by probonopd** [comment] 2017-06-13 18:36
`-qmldir=...` passes the directory to Qt's `qmlimportscanner` which in turn should figure out which QML imports to bundle.

**Closed** 2017-06-20 15:44 UTC
Labels: question

**Comment by orbifx** [comment] 2017-06-20 15:45
I'd like to document this solution in the Wiki.
Is it possible to request a pull for the wiki? Never tried that.

**Comment by TheAssassin** [comment] 2017-06-20 16:55
Well you can clone it, but afaik there's no explicit PR feature. Please try to just edit it va the web editor.

**Comment by orbifx** [comment] 2017-06-21 15:58
I don't have sufficient rights for that.

**Comment by probonopd** [comment] 2017-06-21 18:46
Enabled wiki editing by anyone. @orbifx please try again, thanks.

**Comment by orbifx** [comment] 2017-06-26 14:46
https://github.com/probonopd/linuxdeployqt/wiki/Custom-wrapper-script-instead-of-AppRun

**Comment by probonopd** [comment] 2017-06-26 15:50
Thanks @orbifx

**Comment by lockie** [comment] 2020-05-03 09:58
Does this instruction still apply? appimagetool seems to be overwriting AppRun file to be symlink to what is specified in `Exec=` section of .desktop file no matter what.
